name: nitnem
description: Nitnem App. Please respectfully cover your head and remove your shoes before reciting gurbani.
version: 3.2.0+0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  backdrop: ^0.9.1
  url_launcher: ^6.3.2
  package_info_plus: ^10.2.0
  shared_preferences: ^2.5.5
  intl: ^0.20.2
  battery_plus: ^7.1.0
  wakelock_plus: ^1.7.0
  fl_chart: ^0.70.0
  flutter_riverpod: ^3.3.2
  riverpod_annotation: ^4.0.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  device_frame: ^1.2.0
  integration_test:
    sdk: flutter
  riverpod_generator: ^4.0.0
  freezed: ^3.2.6-dev.1
  build_runner: ^2.4.12
  json_serializable: ^6.9.5

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/khanda.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/khanda.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/themes/
    - assets/path/

  fonts:
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab/RobotoSlab-Regular.ttf
        - asset: assets/fonts/RobotoSlab/RobotoSlab-Bold.ttf

    - family: Sansation
      fonts:
        - asset: assets/fonts/Sansation/Sansation-Regular.ttf
        - asset: assets/fonts/Sansation/Sansation-Italic.ttf
          style: italic
        - asset: assets/fonts/Sansation/Sansation-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/Sansation/Sansation-Bold.ttf

    - family: Kingthings
      fonts:
        - asset: assets/fonts/Kingthings/Kingthings_Calligraphica_Light.ttf
        - asset: assets/fonts/Kingthings/Kingthings_Calligraphica_Italic.ttf
          style: italic
        - asset: assets/fonts/Kingthings/Kingthings_Calligraphica_2.ttf
          weight: 700

    - family: Gurakhar
      fonts:
        - asset: assets/fonts/Gurakhar/GURAKHAR.ttf
        - asset: assets/fonts/Gurakhar/GURAKH_L.ttf
          weight: 400
        - asset: assets/fonts/Gurakhar/GUAK_TH.ttf
          weight: 700

    - family: Gurbanihindi
      fonts:
        - asset: assets/fonts/Gurbanihindi/Gurbanihindi.ttf
